### ISSUE TITLE
Sharing view does not show due to unsatisfied constraints

### ISSUE THREAD

**Issue by nicloay** [natsuite/NatShare-API#75]
I used the latest version with async code and the latest fix (when you don't pause the player while popup is active).

The device where it doesn't work is 13.3 iPad Pro (on another device from the same xcode build it works well)

the error in the console is
```
2020-01-19 19:54:33.738484+0100 appname[1627:2741241] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2808f7700 LPLinkView:0x11e289590.leading == UILayoutGuide:0x281277020'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x2808f7980 H:[LPLinkView:0x11e289590]-(59)-|   (active, names: '|':_UIActivityContentTitleView:0x116bb3540 )>",
    "<NSLayoutConstraint:0x2808eac60 H:|-(0)-[_UIActivityContentTitleView:0x116bb3540]   (active, names: '|':_UINavigationBarContentView:0x11e22c320 )>",
    "<NSLayoutConstraint:0x2808ea710 _UIActivityContentTitleView:0x116bb3540.trailing == _UINavigationBarContentView:0x11e22c320.trailing   (active)>",
    "<NSLayoutConstraint:0x2808e0af0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x11e22c320.width == 6   (active)>",
    "<NSLayoutConstraint:0x2808f7b10 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x281277020'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x116bb3540 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2808f7700 LPLinkView:0x11e289590.leading == UILayoutGuide:0x281277020'UIViewLayoutMarginsGuide'.leading   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-01-19 19:54:42.312911+0100 appname[1627:2741705] [ShareSheet] connection invalidated
2020-01-19 19:54:46.970196+0100 appname[1627:2741241] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2808d9b30 LPLinkView:0x11dc4fb60.leading == UILayoutGuide:0x28127bb80'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x2808d9770 H:[LPLinkView:0x11dc4fb60]-(59)-|   (active, names: '|':_UIActivityContentTitleView:0x11dc4f980 )>",
    "<NSLayoutConstraint:0x2808db110 H:|-(0)-[_UIActivityContentTitleView:0x11dc4f980]   (active, names: '|':_UINavigationBarContentView:0x11dc560b0 )>",
    "<NSLayoutConstraint:0x2808db160 _UIActivityContentTitleView:0x11dc4f980.trailing == _UINavigationBarContentView:0x11dc560b0.trailing   (active)>",
    "<NSLayoutConstraint:0x2808dcbe0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x11dc560b0.width == 6   (active)>",
    "<NSLayoutConstraint:0x2808d9a40 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x28127bb80'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x11dc4f980 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2808d9b30 LPLinkView:0x11dc4fb60.leading == UILayoutGuide:0x28127bb80'UIViewLayoutMarginsGuide'.leading   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by olokobayusuf** [comment]
Try out the latest code from `master`. This issue should be fixed now.

**Comment by nicloay** [comment]
I can not find the ```master```. But what I tried is [this](https://github.com/natsuite/NatShare-API/commits/async) with latest commit ```1a5381afc00ceb3028343daad96d174997f20512```

**Comment by olokobayusuf** [comment]
Yes sorry I misspoke. Are you still facing the issue with the `async` branch?

**Comment by nikolayinnerspace** [comment]
yes. on async branch issue persists (on ipad pro) another devices are good.

**Comment by olokobayusuf** [comment]
Are the logs the same? Can you share them?

**Comment by mdbnet** [comment]
I am experiencing this bug too, through the Unity plug-in. The bug occurs only with iPad Pro and iPad Mini. Could it be due to the aspect ratio of the iPad?

I made a small Unity project that illustrates the bug - https://tactic-forms.s3-us-west-1.amazonaws.com/bugs/ShareButton.zip

**Comment by olokobayusuf** [comment]
[This is a bug in iOS 13](https://stackoverflow.com/questions/58911158/why-is-uiactivityviewcontroller-displaying-auto-constraint-errors-in-console).

**Comment by nicloay** [comment]
If it's a bug in iOS 13 - why another app still able to share images. it seems like the problem is in unity player and share dialogue that they can work together somehow, but not the bug in iOS

**Comment by TimKoppers** [comment]
I have the same issue 

`
2020-02-03 17:43:16.954810+0100 realmoji[44961:7191873] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28294b3e0 _UIActivityActionCellTitleLabel:0x129863460.height >= 22   (active)>",
    "<NSLayoutConstraint:0x28294af30 V:|-(15)-[_UIActivityActionCellTitleLabel:0x129863460]   (active, names: '|':UIView:0x129863130 )>",
    "<NSLayoutConstraint:0x28294af80 V:[_UIActivityActionCellTitleLabel:0x129863460]-(15)-|   (active, names: '|':UIView:0x129863130 )>",
    "<NSLayoutConstraint:0x2829119f0 'UIView-Encapsulated-Layout-Height' UIView:0x129863130.height == 49.3333   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28294b3e0 _UIActivityActionCellTitleLabel:0x129863460.height >= 22   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-02-03 17:43:16.989313+0100 realmoji[44961:7191873] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28294e350 _UIActivityActionCellTitleLabel:0x11e8c4420.height >= 22   (active)>",
    "<NSLayoutConstraint:0x28294dea0 V:|-(15)-[_UIActivityActionCellTitleLabel:0x11e8c4420]   (active, names: '|':UIView:0x11e8c3cf0 )>",
    "<NSLayoutConstraint:0x28294def0 V:[_UIActivityActionCellTitleLabel:0x11e8c4420]-(15)-|   (active, names: '|':UIView:0x11e8c3cf0 )>",
    "<NSLayoutConstraint:0x282911630 'UIView-Encapsulated-Layout-Height' UIView:0x11e8c3cf0.height == 49.3333   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28294e350 _UIActivityActionCellTitleLabel:0x11e8c4420.height >= 22   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-02-03 17:43:16.991182+0100 realmoji[44961:7191873] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x282963020 _UIActivityActionCellTitleLabel:0x129871e50.height >= 22   (active)>",
    "<NSLayoutConstraint:0x282962b70 V:|-(15)-[_UIActivityActionCellTitleLabel:0x129871e50]   (active, names: '|':UIView:0x129871b20 )>",
    "<NSLayoutConstraint:0x282962bc0 V:[_UIActivityActionCellTitleLabel:0x129871e50]-(15)-|   (active, names: '|':UIView:0x129871b20 )>",
    "<NSLayoutConstraint:0x282911db0 'UIView-Encapsulated-Layout-Height' UIView:0x129871b20.height == 49.3333   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x282963020 _UIActivityActionCellTitleLabel:0x129871e50.height >= 22   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
Successfully shared items: False
FaceActing.<CaptureScreen>d__13:System.Collections.IEnumerator.get_Current()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Action:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task`1:TrySetResult(TResult)
System.Threading.Tasks.TaskCompletionSource`1:TrySetResult(TResult)
System.Threading.Tasks.TaskCompletionSource`1:SetResult(TResult)
NatShare.Internal.NativePayload:OnCompletion(IntPtr, Boolean)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2020-02-03 17:43:40.263659+0100 realmoji[44961:7192450] [ShareSheet] connection invalidated
libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper
(lldb) `

**Comment by Klipi** [comment]
I ran into the same issue. I was able to do a workaround by manually setting the source rect when configuring the `UIActivityViewController`, based on this StackOverflow discussion: https://stackoverflow.com/questions/26623893/uiactivityviewcontroller-unable-to-simultaneously-satisfy-constraints-on-devic

Here's a suggestion for the `commit` method in `NSSharePayload.m` (rest of the code is based on the latest commit `7d75992` in NatShare v1.2 branch):

```
- (void) commit {
    // Present share view
    UIActivityViewController* shareController = [UIActivityViewController.alloc initWithActivityItems:payload applicationActivities:nil];
    shareController.modalPresentationStyle = UIModalPresentationPopover;
    shareController.popoverPresentationController.sourceView = sourceViewController.view;
    shareController.view.translatesAutoresizingMaskIntoConstraints = NO; // DEPLOY // iOS 13
    [shareController popoverPresentationController].sourceRect=CGRectMake( 0,200,768,20); // Add this line to work around some iPadOS 13 devices having an error with unsatisfied UI constraints
    [shareController setCompletionWithItemsHandler:^(UIActivityType activityType, BOOL completed, NSArray* returnedItems, NSError* activityError) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (completionHandler)
                completionHandler(completed);
        });
    }];
    [sourceViewController presentViewController:shareController animated:YES completion:nil];
}
```

I directly copied the CGRect size and position from the StackOverflow post, but it's pretty good at least based on my testing. YMMV.

**Comment by olokobayusuf** [comment]
This looks good. Do you mind opening a PR with your changes? Thanks!

**Comment by olokobayusuf** [comment]
Fixed by #82
